name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: runner-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World from GitHub Actions!"

      - name: Print Date
        run: date

      - name: List Files
        run: ls -ltr
